---
- name: Checkout Git repository
  hosts: localhost
  vars:
    git_repo_url: "https://github.com/QEF/q-e.git"
    git_repo_version: "main"
    git_repo_dest: "../workspace"
  tasks:
    - name: Checkout Git repository
      git:
        repo: "{{ git_repo_url }}"
        version: "{{ git_repo_version }}"
        dest: "{{ git_repo_dest }}"