- name: Run terraform destroy
  command: terraform destroy -auto-approve -var aws_access_key="{{ TF_VAR_aws_access_key }}" -var aws_secret_key="{{ TF_VAR_aws_secret_key }}"
  args:
    chdir: ../../terraform
