name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.12'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.12
    - name: Install requirements
      run: |
        pip install -r kvnchv/requirements.txt
        pip install -e kvnchv/
        pip install pytest pytest-cov pytest-assume
    - name: Run pytest
      run: |
        pytest --cov=kvnchv/converger --cov-append --verbose -m "not espresso" kvnchv/tests
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
